### ISSUE TITLE
run prettier on all JS files in a monolithic make-things-pretty PR

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta-dashboard-svelte#119]
> @jdhoffa maybe you could run prettier on all JS files in a monolithic make-things-pretty PR?
> 
> Automatic processes making unrelated changes to PRs makes things more difficult to review/understand/track/etc.

_Originally posted by @cjyetman in https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/115#discussion_r1869579571_

**Comment by jdhoffa** [comment]
I spent about a day doing this already to close https://github.com/RMI-PACTA/pacta-dashboard-svelte/issues/29

I don't plan to do that again. 

I won't approve PRs that have failing CI checks.

**Comment by cjyetman** [comment]
you fixed linting, but you did not fix all the things that prettier wants to force us to do, so now whenever someone touches a JS file, prettier is going to force us to make all these formatting changes to things that have been there since long ago.

I'm not asking to submit PRs with un-pretty or un-linty lines (in the precise changes that I made in that PR). I'm asking that when I submit a PR I'm not forced to fix formatting that is not related to the PR. If you just make it do all the fixes you want it to do now, I'll be happy submitting PRs against the super awesome, beautiful, perfect code that is already there.

**Comment by jdhoffa** [comment]
Please see: https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/115#discussion_r1869928802

That has already been done. 

The changes were not "formatting", and were entirely related to your PR.

**Comment by cjyetman** [comment]
you're mixing up what the linter does and what prettier does.... they're not the same

**Comment by jdhoffa** [comment]
https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/e3f8f5ac01fe4d46321e9febe38a3ed17b889d75/package.json#L13

**Comment by cjyetman** [comment]
you know what `&&` mean, right? 🤣
