### ISSUE TITLE
✨ wire-up embedded data-driven text in various sections

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta-dashboard-svelte#122]
See:

https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/df41b81e621f377f577321ba03c02bf213f2351f/src/routes/portfolio_view.svelte#L186-L188

https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/df41b81e621f377f577321ba03c02bf213f2351f/src/routes/portfolio_view.svelte#L263-L270

**Comment by MonikaFu** [comment]
@jdhoffa can you provide more context here? I don't understand what needs to be done from this ticket.

**Comment by jdhoffa** [comment]
So in the following text:
https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/df41b81e621f377f577321ba03c02bf213f2351f/src/routes/portfolio_view.svelte#L186-L188

The embedded text values `[X]%` and `[Y]%` represent the percent exposure to listed equity and corporate bonds respectively. I understand that Nayra wants those to actually render the percent exposure (that is also shown in the table) rather than bolded placeholders.



https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/df41b81e621f377f577321ba03c02bf213f2351f/src/routes/portfolio_view.svelte#L263-L270

Same here, the embedded text values `[X]%` and `[Y]%` represent `[W]%` and `[Z]%` represent the percentage of:
listed equity (by market value)
corporate bond (by market value)
listed equity (by absolute CO2)
corporate bonds (by absolute CO2

... in PACTA sectors. 

Would be good to replace those placeholders with their values

**Comment by jdhoffa** [comment]
Alternatively we just remove the text altogether as it duplicates info in the charts, which probably isn't necessary

**Comment by jdhoffa** [comment]
But either way, we can't have those placeholders on main 

😊
