### ISSUE TITLE
style: deal with Linter errors

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta-dashboard-svelte#29]
The linter is currently failing: https://github.com/RMI-PACTA/pacta-dashboard-svelte/actions/runs/10422846547/job/28868359633?pr=28

It seems like lots of our JavaScript code has various issues with it (variables defined but never used, etc.)

We should tidy up our JavaScript code, and ideally ensure that the Linter on CI passes

AB#11699

**Comment by MonikaFu** [comment]
yup, agreed. I'd say we should deal with it when we're updating the JS code for resizing etc

**Comment by jdhoffa** [comment]
Agreed
