### ISSUE TITLE
feat: `sector_view.svelte` probably should not have scenario names hard-coded in selector layout

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta-dashboard-svelte#30]
NB: I wonder if it's possible to generate these selectors programmatically. As it stands, the dashboard would only work for 2023 data, and not be generalizable to different years which is not ideal.

_Originally posted by @jdhoffa in https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/28#discussion_r1721327879_

**Comment by MonikaFu** [comment]
Agreed and this will also apply to other selectors actually. They all should be data-driven and not hard-coded I think.

**Comment by MonikaFu** [comment]
ADO: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_sprints/taskboard/P4I/2DegreesInvesting/2024_17?workitem=11679

**Comment by MonikaFu** [comment]
closed with #44
