### ISSUE TITLE
feat: Emission intensity plot has a selectable scenario source and scenario

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta-dashboard-svelte#41]
- depends on https://github.com/RMI-PACTA/workflow.pacta.dashboard/pull/40 (https://github.com/RMI-PACTA/workflow.pacta.dashboard/pull/26 was superseded)

Currently we fix a scenario in the plot but because we now have global selectors it makes more sense to make it possible for the user to select a scenario they want to view in this plot. 

AB#11938

**Comment by MonikaFu** [comment]
FYI @jdhoffa this is a new feature so I am not going to tackle it while re-sizing this plot and removing the filters but it should be added before we release the dashboard.

**Comment by jdhoffa** [comment]
@cjyetman are you able to handle the `worfklow.pacta.dashboard` portion of that? 
do you have enough context to do so?

**Comment by cjyetman** [comment]
> @cjyetman are you able to handle the `worfklow.pacta.dashboard` portion of that? 
> 
> do you have enough context to do so?

I think so. I'll give it a go.
