### ISSUE TITLE
feat: add "absolute/relative" toggle to portfolio-level technology mix

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta-dashboard-svelte#77]
In the interactive report, it is possible to toggle this plot, to be able to show the technology mix both in absolute terms (understanding the portion it occupies of the portfolio) and relative terms.

In the dashboard, I see only the former:
<img width="1219" alt="Screenshot 2024-11-28 at 14 07 23" src="https://github.com/user-attachments/assets/566703ac-8c01-4e31-904e-51e06632d3a6">

I found the full-screen bar view very useful to dive deeper into each technology mix, we might consider adding in that functionality

**Comment by MonikaFu** [comment]
this view is available in the 'sector view' tab as that tab is more aimed to be a deep dive view. I removed it from the portfolio view since it's an 'overview' and to my mind it made more sense to not have any selectables in this page.

**Comment by jdhoffa** [comment]
That makes sense!
Closing without action.
