### ISSUE TITLE
Add individual titles to pie charts

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta-dashboard-svelte#88]
Currently it is not clear enough which pie chart is about value exposure and which one is about emissions.

![image](https://github.com/user-attachments/assets/16e61710-4278-4110-80fa-93b6933fb994)

AB#12273

**Comment by cjyetman** [comment]
First, it may be just as reasonable to add titles above these in svelte, however that works, e.g. adding another row of text just below "Corporate bonds portion of the portfolio".

This wouldn't be very hard in D3/JavaScript, though proper positioning and sizing of it could be difficult especially considering the responsive sizing of the plots (currently, it's quite easy for me to shrink my browser window to the point that the text in the pie charts is too small to be readable), whereas the svelte/html/whatever titles maintain their size while the positioning adjusts (though currently, if the browser window is narrow enough, it switches to a single column and then you see both titles together at the top, which is a bit nonsensical).

You would just want to append another text element, set the text, and position it appropriately, much like is done here with the annotations (and likely you'd want to do it in the same place too)

https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/ed95a2ba311d79c0b2783726e29da2070b6987d0/src/js/pie_exploded.js#L176-L191
