### ISSUE TITLE
Exposure statistics: bold out the asset class name for sector exposure

### ISSUE THREAD

**Issue by MonikaFu** [RMI-PACTA/pacta-dashboard-svelte#90]
Making 'Corporate bonds' bold in this case would draw attention of the user more to the fact that the percentage is of the asset class portion of the portfolio and not the entire portfolio.

![image](https://github.com/user-attachments/assets/9bb03645-bcf8-4f2a-acfb-75a5a20fd8b5)

AB#12275

**Comment by cjyetman** [comment]
I think if you add this

``` javascript
.style('font-weight', (d, i) => i == 2 ? 'bold' : 'normal')
```

to the end of this block
https://github.com/RMI-PACTA/pacta-dashboard-svelte/blob/ed95a2ba311d79c0b2783726e29da2070b6987d0/src/js/exposure_stats.js#L104-L115

with the logic that the 2nd element of the data, `asset_class`, will get `font-weight: bold` added to its `style` attribute, and the first and third will get `font-weight: normal` leaving them unchanged (assuming there's no other CSS already changing them).

**Comment by jdhoffa** [comment]
> ```js
> .style('font-weight', (d, i) => i == 2 ? 'bold' : 'normal')
> ```

Can I ask why we need both `d` and `i` there?

**Comment by jdhoffa** [comment]
Implemented and it seems to work in https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/106

**Comment by cjyetman** [comment]
> > ```js
> > .style('font-weight', (d, i) => i == 2 ? 'bold' : 'normal')
> > ```
> 
> Can I ask why we need both `d` and `i` there?

The first argument passed to the arrow function will be the element/item, and second will be the iterator/index. You don't really have a choice with that (that's what D3's `.style()` does), but you can name them whatever you want (though `d` and `i` are very common), e.g. 

```js
.style('font-weight', (elem, idx) => idx == 2 ? 'bold' : 'normal')
```
